# Generated by Django 4.0.6 on 2023-03-24 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import user.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateField(auto_now_add=True)),
                ('app_name', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(choices=[('Computer Literacy', 'Computer Literacy'), ('Applications Training', 'Applications Training'), ('Frontend Training', 'Frontend Training'), ('Backend Training', 'Backend Training')], max_length=100, null=True)),
                ('logo', models.ImageField(default='avatar.jpg', upload_to='profile_images')),
                ('date', models.DateField(null=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('category', models.CharField(blank=True, choices=[('COMPT. LIT. FORM', 'COMPT. LIT. FORM'), ('APP. TRN. FORM', 'APP. TRN. FORM'), ('FRNTEND TRN FORM', 'FRNTEND TRN FORM'), ('BCKEND. TRN. FORM', 'BCKEND. TRN. FORM'), ('COMPT. LIT. TRN. FEE', 'COMPT. LIT. TRN. FEE'), ('APP. TRN. FEE', 'APP. TRN. FEE'), ('FRNTEND. TRN. FEE', 'FRNTEND. TRN. FEE'), ('BCKEND. TRN. FEE', 'BCKEND. TRN. FEE'), ('PROJ. BASED. AGREE. FORM', 'PROJ. BASED. AGREE. FORM')], default=None, max_length=100, null=True)),
                ('added_date', models.DateField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.course')),
            ],
        ),
        migrations.CreateModel(
            name='Studentcourse',
            fields=[
                ('courseid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('added_date', models.DateField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='user.course')),
                ('student', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='user.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=20, null=True)),
                ('othernames', models.CharField(max_length=40, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('mstatus', models.CharField(blank=True, choices=[('Single', 'Single'), ('Mariage', 'Mariage'), ('Diovioce', 'Diovioce')], max_length=20, null=True)),
                ('age', models.CharField(max_length=3, null=True)),
                ('image', models.ImageField(default='avatar.jpg', upload_to='profile_images')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(choices=[('Secondary School', 'Secondary School'), ('OND', 'OND'), ('ND', 'ND'), ('NCE', 'NCE'), ('HND', 'HND'), ('Degree', 'Degree')], default=None, max_length=60, null=True)),
                ('instition', models.CharField(max_length=200, null=True)),
                ('graduation', models.CharField(max_length=100, null=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contactdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_origin', models.CharField(max_length=30, null=True)),
                ('lga_origin', models.CharField(max_length=30, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('home_town', models.CharField(max_length=30, null=True)),
                ('village', models.CharField(max_length=30, null=True)),
                ('permanent_address', models.CharField(max_length=30, null=True)),
                ('contact_person', models.CharField(max_length=30, null=True)),
                ('contact_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('contact_occupation', models.CharField(max_length=30, null=True)),
                ('contact_relationship', models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Uncle', 'Uncle'), ('Auntie', 'Auntie'), ('Brother', 'Brother'), ('Sister', 'Sister'), ('Others', 'Others')], max_length=30, null=True)),
                ('applicant', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
            ],
        ),
        migrations.AddField(
            model_name='applicant',
            name='course_ticket',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='user.course'),
        ),
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('value', models.CharField(blank=True, default=user.models.generate_pin, max_length=6)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='Not Activated', max_length=30)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.ticket')),
            ],
            options={
                'unique_together': {('ticket', 'value')},
            },
        ),
    ]
