# Generated by Django 4.0.6 on 2023-01-16 03:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(choices=[('Computer Literacy', 'Computer Literacy'), ('Applications Training', 'Applications Training'), ('Frontend Training', 'Frontend Training'), ('Backend Training', 'Backend Training')], max_length=100, null=True)),
                ('form_fee', models.CharField(max_length=200)),
                ('course_fee', models.CharField(max_length=200)),
                ('logo', models.ImageField(default='avatar.jpg', upload_to='profile_images')),
                ('added_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=20, null=True)),
                ('othernames', models.CharField(max_length=40, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('image', models.ImageField(default='avatar.jpg', upload_to='profile_images')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
