# Generated by Django 4.0.6 on 2023-03-24 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='date',
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(choices=[('THREE MONTHS', 'THREE MONTHS'), ('SIX MONTHS', 'SIX MONTHS'), ('NINE MONTHS', 'NINE MONTHS')], max_length=100, null=True),
        ),
    ]
