# Generated by Django 4.0.6 on 2023-03-25 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0004_alter_contactdetails_applicant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetails',
            name='contact_occupation',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contactdetails',
            name='contact_person',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='contactdetails',
            name='permanent_address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contactdetails',
            name='state_origin',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.CreateModel(
            name='tsessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tsession', models.CharField(choices=[('MORNING', 'MORNING'), ('EVENING', 'EVENING'), ('NIGHT ONLINE', 'NIGHT ONLINE')], default=None, max_length=200, null=True)),
                ('tdays', models.CharField(choices=[('MONDAY - FRIDAY', 'MONDAY - FRIDAY'), ('WEEKENDS', 'WEEKENDS')], default=None, max_length=200, null=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
