# Generated by Django 4.0.6 on 2023-03-25 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_contactdetails_contact_occupation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tsessions',
            old_name='tdays',
            new_name='training_days',
        ),
        migrations.RemoveField(
            model_name='tsessions',
            name='tsession',
        ),
        migrations.AddField(
            model_name='tsessions',
            name='training_session',
            field=models.CharField(choices=[('MORNING SESSION', 'MORNING SESSION'), ('EVENING SESSION', 'EVENING SESSION'), ('ONLINE NIGHT SESSION', 'ONLINE NIGHT SESSION')], default=None, max_length=200, null=True),
        ),
    ]
