# Generated by Django 4.0.6 on 2023-04-11 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_tdays_tsessions_training_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
        migrations.AlterField(
            model_name='education',
            name='qualification',
            field=models.CharField(choices=[('Secondary School', 'Secondary School'), ('OND', 'OND'), ('ND', 'ND'), ('HND', 'HND'), ('NCE', 'NCE'), ('Degree', 'Degree')], default=None, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Diovioced', 'Diovioced')], max_length=20, null=True),
        ),
    ]
