# Generated by Django 4.0.6 on 2023-04-11 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0008_questionnaire'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionnaire',
            old_name='browseint',
            new_name='can_browse_internet',
        ),
        migrations.RenameField(
            model_name='questionnaire',
            old_name='computerkn',
            new_name='computer_knowledge',
        ),
        migrations.RenameField(
            model_name='questionnaire',
            old_name='knowwebdev',
            new_name='know_programming',
        ),
        migrations.RenameField(
            model_name='questionnaire',
            old_name='littleprogram',
            new_name='know_web_development',
        ),
        migrations.RenameField(
            model_name='questionnaire',
            old_name='ownlaptop',
            new_name='own_a_laptop',
        ),
        migrations.RenameField(
            model_name='questionnaire',
            old_name='ownphone',
            new_name='own_a_phone',
        ),
        migrations.CreateModel(
            name='Submitted',
            fields=[
                ('application', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('confirm', models.BooleanField()),
                ('approved', models.CharField(default='Not Approved', max_length=20, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
