# Generated by Django 4.0.6 on 2023-04-12 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_rename_browseint_questionnaire_can_browse_internet_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionnaire',
            old_name='can_browse_internet',
            new_name='browse_internet',
        ),
        migrations.RenameField(
            model_name='questionnaire',
            old_name='know_web_development',
            new_name='own_laptop',
        ),
        migrations.RenameField(
            model_name='questionnaire',
            old_name='own_a_laptop',
            new_name='own_phone',
        ),
        migrations.RenameField(
            model_name='questionnaire',
            old_name='own_a_phone',
            new_name='web_development',
        ),
    ]
