# Generated by Django 4.0.6 on 2023-04-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_remove_questionnaire_browse_internet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='browse_internet',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='know_programming',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='learn_night',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='own_laptop',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='own_phone',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
