# Generated by Django 4.0.6 on 2023-07-04 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_questionnaire_browse_internet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(blank=True, choices=[('Computer Litracy Application Form', 'Computer Litracy Application Form'), ('Computer Applications Training Form', 'Computer Applications Training Form'), ('Front-End Web Development Form', 'Front-End Web Development Form'), ('Backend Training Fee', 'Backend Training Fee'), ('Computer. Lit. Training Fee', 'Computer. Lit. Training Fee'), ('APP. Training Fee', 'APP. Training Fee'), ('Frontend Training Fee', 'Frontend Training Fee'), ('Frontend Scholarship Training', 'Frontend Scholarship Training'), ('Backend. Training Fee', 'Backend. Training Fee'), ('Project-Based Training Agreement Form', 'Project-Based Training Agreement Form')], default=None, max_length=255, null=True),
        ),
    ]
