# Generated by Django 4.0.6 on 2023-07-04 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0013_alter_ticket_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('staff_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('staff_role', models.CharField(blank=True, choices=[('Instructor', 'Instructor'), ('Computer Operator', 'Computer Operator'), ('Cashier', 'Cashier')], default=None, max_length=20, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('staff_user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
