# Generated by Django 4.0.6 on 2023-07-04 08:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0014_instructor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Instructor',
            new_name='Employee',
        ),
    ]
