# Generated by Django 4.0.6 on 2023-07-07 11:25

from django.db import migrations
import imagekit.models.fields
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_rename_instructor_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(default='avatar.jpg', upload_to='profile_images', validators=[user.models.FileExtensionValidator(['jpeg', 'jpg', 'gif', 'png'])]),
        ),
    ]
